BitBookLoginApp/BitBookLoginApp/Models/ImageGallery.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BitBookLoginApp.Models
{
    public class ImageGallery
    {
        public ImageGallery()
        {
            ImageList = new List<string>();   
        }
        [Key]
        public Guid ID { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public List<string> ImageList { get; set; }
    }
}

BitBookLoginApp/BitBookLoginApp/Controllers/ImageGalleryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BitBookLoginApp.Models;

namespace BitBookLoginApp.Controllers
{
    public class ImageGalleryController : Controller
    {
        private BitBookDbContext db = new BitBookDbContext();
        //
        // GET: /ImageGallery/
        public ActionResult Index()
        {
            var imagesModel = new ImageGallery();
            var imageFiles = Directory.GetFiles(Server.MapPath("~/Upload_Files/"));
            foreach (var item in imageFiles)
            {
                imagesModel.ImageList.Add(Path.GetFileName(item));
            }
            return View(imagesModel);
        }

        [HttpGet]
        public ActionResult UploadImage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadImageMethod()
        {
            if (Request.Files.Count != 0)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i];
                    int fileSize = file.ContentLength;
                    string fileName = file.FileName;
                    file.SaveAs(Server.MapPath("~/Upload_Files/" + fileName));
                    ImageGallery imageGallery = new ImageGallery();
                    imageGallery.ID = Guid.NewGuid();
                    imageGallery.Name = fileName;
                    imageGallery.ImagePath = "~/Upload_Files/" + fileName;
                    db.ImageGalleries.Add(imageGallery);
                    db.SaveChanges();
                }
                return Content("Success");
            }
            return Content("failed");
        }





    }
}

BitBookLoginApp/BitBookLoginApp/Views/ImageGallery/Index.cshtml
@model BitBookLoginApp.Models.ImageGallery
@{
    ViewBag.Title = "Image Gallery Page";
}
@*<script src="~/Scripts/jquery-1.8.2.min.js"></script>*@
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.mousewheel-3.0.6.pack.js"></script>
<script src="~/Scripts/jquery.fancybox.js?v=2.1.3"></script>
<link href="~/Content/jquery.fancybox.css?v=2.1.2" rel="stylesheet" media="screen" />
<link href="~/Scripts/jquery.fancybox.css" rel="stylesheet" />

<script type="text/javascript">
    $(document).ready(function () {
        $("#ShowImage").fancybox({
            helpers:
            {
                title:
                {
                    type: 'float'
                }
            }
        });
    });
</script>
<style type="text/css">
    .imgBox {
        width: 200px;
        height: 200px;
        opacity: 1.0;
        filter: alpha(opacity=100);
    }

        .imgBox:hover {
            -moz-box-shadow: 0 0 10px #ccc;
            -webkit-box-shadow: 0 0 10px #ccc;
            box-shadow: 0 0 10px #ccc;
            opacity: 0.4;
            filter: alpha(opacity=40);
        }
</style>
<div class="jumbotron" style="height:600px;">
    <p>
        <a class="imageGallery btn btn-primary" data-fancybox-type="iframe"
           href="@Url.Action("UploadImage","ImageGallery")">Upload New Image</a>
    </p>
    <div style="border-bottom:1px solid Red;"></div>
    @if (Model.ImageList.Count > 0)
    {
        <div class="row-fluid">
            <div class="span2">
                <div class="item">
                    @foreach (var image in Model.ImageList)
                    {
                        <div style=" margin:10px; float:left; height:200px; overflow:hidden; width:200px;">
                            <a id="ShowImage" class="fancybox-button" data-rel="fancybox-button"
                               title="Photo" href="@Url.Content("~/Upload_Files/"+ image)">
                                <div class="zoom">
                                    <img src="@Url.Content("~/Upload_Files/" + image)" class="imgBox" />
                                    <div class="zoom-icon"></div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.imageGallery').fancybox({
            fitToView: false,
            width: '600px',
            height: '400px',
            autoSize: false,
            closeClick: false,
            openEffect: 'none',
            closeEffect: 'none',
            padding: 0,
            closeBtn: false,
            'afterClose': function () {
                window.location.reload();
            },
        });
    });
</script>

BitBookLoginApp/BitBookLoginApp/Views/ImageGallery/UploadImage.cshtml
@model BitBookLoginApp.Models.ImageGallery
@{
    ViewBag.Title = "Upload Image";
    Layout = null;
}
<html>
<head>
    <title>Image Gallery</title>
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script type="text/javascript">
        window.onload = function () {
            document.getElementById('imageUploadId').onsubmit = function () {
                var formdata = new FormData();
                var fileInput = document.getElementById('fileInputType');
                for (i = 0; i < fileInput.files.length; i++) {
                    formdata.append(fileInput.files[i].name, fileInput.files[i]);
                }
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/ImageGallery/UploadImageMethod');
                xhr.send(formdata);
                xhr.onreadystatechange = function () {
                    if (xhr.readyState == 4 && xhr.status == 200) {
                        if (xhr.responseText == "Success") {
                            alert("Upload image successfully.");
                            parent.jQuery.fancybox.close();
                        } else {
                            alert("Error occurred.! Please try again");
                        }
                    }
                }
                return false;
            }
        }
    </script>

</head>
<body style="background-color:#fff">
    <div style="height:400px; border:1px solid;">
        <div style="width: 100%; height: 50px; border-bottom: 1px solid #808080; background-color: #3A579A; ">
            <div style="float:right; height:30px; width:30px; margin-top:10px;
                border-left:0px solid #c8c8c8">
                <a href="javascript:parent.jQuery.fancybox.close();"
                   style="color: orange; cursor: pointer; text-decoration: none;">
                    <img src="../Content/fullscreenButton.png">
                </a>
            </div>
        </div>
        <div>
            <div style="margin-left:80px; float:left; width:500px;
                                                                                                                                                                                    height:270px; border: 0px solid black;">
                <div>
                    <br />
                    <form id="imageUploadId">
                        <h3>Upload a picture</h3>
                        <input id="fileInputType" type="file" multiple class="fileUpload"
                               style="width:300px;"><br />
                       
                        <input type="submit" class="btn btn-success" value="Image Upload" />
                    </form>
                </div>
            </div>
        </div>
       
        <div style="width:100%; margin-top:290px; border-bottom:1px solid #808080"></div>
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
        <div style="background-color: #3A579A; height: 57px; margin-top: -20px;">
            <div style="text-align:center; margin-top:20px;"><p>2014 &copy; ImplementSoft</p></div>
        </div>

       

    </div>
</body>
</html>